version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "nocombine"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      lint:
        patterns:
          - "eslint*"
          - "prettier*"
          - "@typescript-eslint/*"
      test:
        patterns:
          - "jest*"
          - "@jest/*"
          - "@swc/jest*"
          - "tsd"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "ci"
